# Generated by Django 4.1.4 on 2023-06-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliancesProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='BabyProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('diapering', 'DIAPERING'), ('feeding', 'FEEDING'), ('toys', 'TOYS')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='ComputingProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('computers', 'COMPUTER'), ('data storage', 'DATA STORAGE'), ('printers', 'PRINTERS')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('televisions & video', 'TELEVISION & VIDEO'), ('home audio', 'HOME AUDIO'), ('Generator', 'GENERATOR & PORTABLE POWER')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='FashionProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('women', "WOMEN'S FASHION"), ('men', "MEN'S FASHION"), ('kid', "KID'S FASHION"), ('all', 'ALL FASHION'), ('watch', 'WATCHES'), ('glass', 'GLASSES')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='GameProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('accessories', 'ACCESSORIES')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='HealthBeautyProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('make up', 'MAKE UP'), ('personal care', 'PERSONAL CARE'), ('fragrances', 'FRAGRANCES'), ('hair care', 'HAIR CARE'), ('oral care', 'ORAL CARE'), ('health care', 'HEALTH CARE')], default=True, max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='IndoorProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('home & kitchen', 'HOME& KITCHEN'), ('office', 'OFFICE PRODUCTS'), ('home & office furniture', 'HOME & OFFICE FURNITURE')], max_length=30, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('mobile', 'MOBILE PHONES'), ('mobile accessories', 'MOBILE ACCESSOORIES'), ('tablets', 'TABLETS')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='SportProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('gear', 'GEAR'), ('cardio training', 'CARDIO TRAINING'), ('team sport', 'TEAM SPORT')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
        migrations.CreateModel(
            name='SupermarketProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.product')),
                ('sub_category', models.CharField(blank=True, choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], max_length=20, null=True)),
            ],
            bases=('main.product',),
        ),
    ]
