# Generated by Django 4.1.4 on 2023-06-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliancesproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('small appliances', 'SMALL APPLIANCES'), ('large appliances', 'LARGE APPLIANCES')], default=None, max_length=20, null=True),
        ),
    ]
