# Generated by Django 4.1.4 on 2023-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_appliancesproduct_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babyproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('diapering', 'DIAPERING'), ('feeding', 'FEEDING'), ('toys', 'TOYS')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='computingproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('computers', 'COMPUTER'), ('data storage', 'DATA STORAGE'), ('printers', 'PRINTERS')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='electronicsproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('televisions & video', 'TELEVISION & VIDEO'), ('home audio', 'HOME AUDIO'), ('Generator', 'GENERATOR & PORTABLE POWER')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fashionproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('women', "WOMEN'S FASHION"), ('men', "MEN'S FASHION"), ('kid', "KID'S FASHION"), ('all', 'ALL FASHION'), ('watch', 'WATCHES'), ('glass', 'GLASSES')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gameproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('accessories', 'ACCESSORIES')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='healthbeautyproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('make up', 'MAKE UP'), ('personal care', 'PERSONAL CARE'), ('fragrances', 'FRAGRANCES'), ('hair care', 'HAIR CARE'), ('oral care', 'ORAL CARE'), ('health care', 'HEALTH CARE')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='indoorproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('home & kitchen', 'HOME& KITCHEN'), ('office', 'OFFICE PRODUCTS'), ('home & office furniture', 'HOME & OFFICE FURNITURE')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('mobile', 'MOBILE PHONES'), ('mobile accessories', 'MOBILE ACCESSOORIES'), ('tablets', 'TABLETS')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sportproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('gear', 'GEAR'), ('cardio training', 'CARDIO TRAINING'), ('team sport', 'TEAM SPORT')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supermarketproduct',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20, null=True),
        ),
    ]
