# Generated by Django 4.1.4 on 2023-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_appliancesproduct_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancesproduct',
            name='sub_category',
            field=models.CharField(choices=[('small appliances', 'SMALL APPLIANCES'), ('large appliances', 'LARGE APPLIANCES')], default=1, max_length=20, null=True),
        ),
    ]
