# Generated by Django 4.1.4 on 2023-06-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('supermarket', 'SUPERMARKET'), ('health&beauty', 'HEALTH & BEAUTY'), ('home&office', 'HOME & OFFICE'), ('appliances', 'APPLIANCES'), ('phones&tablets', 'PHONE & TABLETS'), ('computing', 'COMPUTING'), ('eletronics', 'ELECTRONICS'), ('fashion', 'FASHION'), ('Baby product', 'BABY PRODUCTS'), ('gaming', 'GAMING'), ('sporting goods', 'SPORTING GOODS'), ('other categories', 'OTHER CATEGORIES')], max_length=100),
        ),
    ]
