# Generated by Django 4.1.4 on 2023-06-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_supermarketproduct_sportingproduct_phoneproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliances_product',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='babyproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='computingproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='electronics_product',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='fashionproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='gamingtingproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='healthbeautyproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='indoorproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='sportingproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='supermarketproduct',
            name='sub_category',
            field=models.CharField(choices=[('food cupboard', 'FOOD'), ('beverages', 'BEVERAGES'), ('beer', 'BEER, WINE & SPIRITS'), ('baby product', 'BABY PRODUCT')], default=None, max_length=20),
        ),
    ]
