# Generated by Django 4.1.4 on 2023-06-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
