# Generated by Django 4.1.4 on 2023-06-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_appliances_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appliances_Product',
            new_name='AppliancesProduct',
        ),
        migrations.AlterField(
            model_name='healthbeautyproduct',
            name='sub_category',
            field=models.CharField(choices=[('make up', 'MAKE UP'), ('personal care', 'PERSONAL CARE'), ('fragrances', 'FRAGRANCES'), ('hair care', 'HAIR CARE'), ('oral care', 'ORAL CARE'), ('health care', 'HEALTH CARE')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='indoorproduct',
            name='sub_category',
            field=models.CharField(choices=[('home & kitchen', 'HOME& KITCHEN'), ('office', 'OFFICE PRODUCTS'), ('home & office furniture', 'HOME & OFFICE FURNITURE')], default=None, max_length=30),
        ),
    ]
