# Generated by Django 4.1.4 on 2023-06-10 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_appliances_product_appliancesproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('televisions & video', 'TELEVISION & VIDEO'), ('home audio', 'HOME AUDIO'), ('Generator', 'GENERATOR & PORTABLE POWER')], default=None, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacture_by', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink')], max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='GameProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacture_by', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink')], max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='SportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(choices=[('gear', 'GEAR'), ('cardio training', 'CARDIO TRAINING'), ('team sport', 'TEAM SPORT'), ('training', 'STRENGTH TRAINING EQUIPMENT')], default=None, max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacture_by', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink')], max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamingtingproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sportingproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('supermarket', 'SUPERMARKET'), ('health&beauty', 'HEALTH & BEAUTY'), ('home&office', 'HOME & OFFICE'), ('appliances', 'APPLIANCES'), ('phones&tablets', 'PHONE & TABLETS'), ('computing', 'COMPUTING'), ('eletronics', 'ELECTRONICS'), ('fashion', 'FASHION'), ('Baby product', 'BABY PRODUCTS'), ('gaming', 'GAMING'), ('sporting goods', 'SPORTING GOODS'), ('other categories', 'OTHER CATEGORIES')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='appliancesproduct',
            name='sub_category',
            field=models.CharField(choices=[('small appliances', 'SMALL APPLIANCES'), ('large appliances', 'LARGE APPLIANCES')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='babyproduct',
            name='sub_category',
            field=models.CharField(choices=[('diapering', 'DIAPERING'), ('feeding', 'FEEDING'), ('toys', 'TOYS'), ('bathing', 'BATHING & SKIN CARE')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='computingproduct',
            name='sub_category',
            field=models.CharField(choices=[('computers', 'COMPUTER'), ('data storage', 'DATA STORAGE'), ('printers', 'PRINTERS')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='fashionproduct',
            name='sub_category',
            field=models.CharField(choices=[('women', "WOMEN'S FASHION"), ('men', "MEN'S FASHION"), ('kid', "KID'S FASHION"), ('all', 'ALL FASHION'), ('watch', 'WATCHES'), ('glass', 'GLASSES')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='sub_category',
            field=models.CharField(choices=[('mobile', 'MOBILE PHONES'), ('mobile accessories', 'MOBILE ACCESSOORIES'), ('tablets', 'TABLETS')], default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='Electronics_Product',
        ),
        migrations.DeleteModel(
            name='GamingtingProduct',
        ),
        migrations.DeleteModel(
            name='SportingProduct',
        ),
    ]
