# Generated by Django 4.1.4 on 2023-06-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_electronicsproduct_gameproduct_sportproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='computingproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='electronicsproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fashionproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gameproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='healthbeautyproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='indoorproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sportproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supermarketproduct',
            name='category',
        ),
        migrations.DeleteModel(
            name='AppliancesProduct',
        ),
        migrations.DeleteModel(
            name='BabyProduct',
        ),
        migrations.DeleteModel(
            name='ComputingProduct',
        ),
        migrations.DeleteModel(
            name='ElectronicsProduct',
        ),
        migrations.DeleteModel(
            name='FashionProduct',
        ),
        migrations.DeleteModel(
            name='GameProduct',
        ),
        migrations.DeleteModel(
            name='HealthBeautyProduct',
        ),
        migrations.DeleteModel(
            name='IndoorProduct',
        ),
        migrations.DeleteModel(
            name='PhoneProduct',
        ),
        migrations.DeleteModel(
            name='SportProduct',
        ),
        migrations.DeleteModel(
            name='SupermarketProduct',
        ),
    ]
