# Generated by Django 4.1.4 on 2023-07-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
